name: Create Feature, Bugfix, or Hotfix Branch and Update Version

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of version update: patch, minor, or major'
        required: true
        default: 'patch'
      branch_type:
        description: 'Type of branch: feature, bugfix, or hotfix'
        required: true
        default: 'feature'

permissions:
  contents: write

jobs:
  create-branch-and-update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get current version from package.json
        id: get_version
        run: |
          # Lê a versão atual do package.json
          VERSION=$(jq -r '.version' package.json)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Increment version based on input type
        run: |
          # Extraí a versão atual
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ env.VERSION }}"
          echo "Env version: ${{ env.VERSION }}"

          # Incrementa a versão conforme o tipo
          if [[ "${{ inputs.type }}" == "major" ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [[ "${{ inputs.type }}" == "minor" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          # Nova versão
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"

          # Atualiza o package.json com a nova versão
          jq --arg version "$NEW_VERSION" '.version = $version' package.json > package.tmp.json
          mv package.tmp.json package.json

          # Commit e push do package.json atualizado
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: update version to $NEW_VERSION"
          git push origin HEAD

      - name: Create the new branch
        run: |
          BRANCH_NAME="${{ inputs.branch_type }}/$NEW_VERSION"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
