name: Create Feature, Bugfix, or Hotfix Branch from Selected Release and Update Version

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of version update: patch, minor, or major'
        required: true
        default: 'patch'
      branch_type:
        description: 'Type of branch: feature, bugfix, or hotfix'
        required: true
        default: 'feature'
      source_branch:
        description: 'The release branch from which the new branch will be created (e.g., release/1.0.0)'
        required: true
        default: 'release/1.0.0'

permissions:
  contents: write

jobs:
  create-branch-from-selected-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout the selected release branch
        run: |
          echo "Checking out the branch: ${{ inputs.source_branch }}"
          git fetch --all
          git checkout "origin/${{ inputs.source_branch }}"
          git pull origin "${{ inputs.source_branch }}"

      - name: Get the release version
        id: get_release_version
        run: |
          # A versão da release será obtida diretamente do nome da branch fornecida
          RELEASE_VERSION="${{ inputs.source_branch }}" 
          RELEASE_VERSION=${RELEASE_VERSION//release\//}  # Remove o prefixo "release/"
          echo "Release version: $RELEASE_VERSION"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Increment version based on input type
        run: |
          # Extrai a versão da release selecionada
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ env.RELEASE_VERSION }}"

          # Incrementa a versão conforme o tipo
          if [[ "${{ inputs.type }}" == "major" ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [[ "${{ inputs.type }}" == "minor" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"

          jq --arg version "$NEW_VERSION" '.version = $version' package.json > package.tmp.json
          mv package.tmp.json package.json

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: update version to $NEW_VERSION"

          # git push origin HEAD

          BRANCH_NAME="${{ inputs.branch_type }}/$NEW_VERSION"
          echo "Creating new branch: $BRANCH_NAME"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
